version: "3.7"

services:
  postgres:
    image: postgis/postgis:12-master
    container_name: "${MAPNOTES_API_DB_NAME:-mapnotes_api}-db"
    ports:
      - "${MAPNOTES_API_DB_PORT:-5432}:5432"
    environment:
      - "POSTGRES_DB=${MAPNOTES_API_DB_NAME:-mapnotes_api}"
      - "POSTGRES_USER=${MAPNOTES_API_DB_USER:-mapnotes_api_user}"
      - "POSTGRES_PASSWORD=${MAPNOTES_API_DB_PASSWORD:-password}"
